### ISSUE TITLE
High CPU and GPU usage.

### ISSUE THREAD

**Issue by DevAgu93** [EpicGames/raddebugger#125]
While not minimized
![image](https://github.com/EpicGames/raddebugger/assets/63572671/d4bd73a1-142b-4afd-8e79-ba56f82ddf80)
While minimized
![image](https://github.com/EpicGames/raddebugger/assets/63572671/47042499-e44d-4d1d-8dd8-3edbb9292640)

I use a low end machine. It can be tough to use while having other apps opened.
My specs are:
12 gb of ram and AMD Radeon R5 gpu
Processor AMD A6-7480 Radeon R5, 8 Compute Cores 2C+6G     3.50 GHz

**Comment by ryanfleury** [comment]
Most of the CPU/GPU work should be completely halted if the debugger is not actively being interacted with, and if there are no debug events being received. I just fixed a bug w.r.t. this in fe5f38c3066bf5b50b55ab9d2bf724a863233ddd. But to see what the performance characteristics are like when the debugger is actually correctly sleeping, can you show CPU/GPU usage when your target is paused, and the debugger is minimized?

**Comment by DevAgu93** [comment]
![image](https://github.com/EpicGames/raddebugger/assets/63572671/13af856d-e2f0-4b3e-a9fe-eb921501999b)
Everything seems fine while paused and minimized

**Comment by ryanfleury** [comment]
Can you try the top of the `dev` branch, and let me know if this continues being an issue? It should behave identically even if it isn't minimized, if nothing is happening (including if e.g. the target is running). The bug I fixed was keeping the debugger constantly refreshing under some conditions, notably when initially running a target. If you're pushing out lots of debug events, e.g. via `OutputDebugString` or other various exceptions, then currently the assumption is that the debugger will need to update and re-render, but otherwise it should be quiet under normal conditions.

**Comment by DevAgu93** [comment]
Not minimized
![image](https://github.com/EpicGames/raddebugger/assets/63572671/0fbbf56e-1686-4521-b5fd-48318b398609)
Minimized
![image](https://github.com/EpicGames/raddebugger/assets/63572671/77aa327b-30fe-49e7-bc91-8cebb1de2f6f)
27% gpu usage now, but up to 77% cpu usage

**Comment by ryanfleury** [comment]
Two questions: (a) is your game listed hierarchically under `raddbg.exe` in this case? and (b) what does your `Output` tab look like?

**Comment by DevAgu93** [comment]
![image](https://github.com/EpicGames/raddebugger/assets/63572671/7307d134-e4c7-466d-9be4-6b88f8f512eb)
a_ Yes it is.
b_ I output debug messages but only while opening. It's not constantly outputting anything else.

**Comment by ryanfleury** [comment]
Can you show me how the CPU/GPU usage breaks down between RADDBG and your game by expanding the entry in Task Manager, so that we can understand how the cost breaks down a bit more?

**Comment by DevAgu93** [comment]
![image](https://github.com/EpicGames/raddebugger/assets/63572671/aff13cf2-98dc-487d-b2fa-3af53b436193)
Sorry. Is this what you meant with expanding?

**Comment by ryanfleury** [comment]
I just found a bug relating to this, so I will push a fix shortly...

**Comment by DevAgu93** [comment]
![image](https://github.com/EpicGames/raddebugger/assets/63572671/611cfa9e-82ec-4f19-94c1-bbd2793fe7e6)
It keeps bobbing.

**Comment by ryanfleury** [comment]
Okay, great. That is the primary problem. The CPU/GPU usage of the debugger *as it is actively updating* could be better, but that is a kind of forever-issue which we can improve overtime. But focusing on that part isn't particularly high priority, since it should only be using CPU/GPU (mostly) if it's actively being interacted with, or if it's actively updating.

I just pushed a fix for that constant bobbing to `dev`. Can you double check that it's fixed on your end, and that the debugger's CPU/GPU usage is gone while you're not interacting with it?

**Comment by DevAgu93** [comment]
Still not sleeping. In this video I'm hovering the mouse on the game but it's still selecting lines on the debugger.
https://github.com/EpicGames/raddebugger/assets/63572671/fd2c0d56-f9e0-4d81-a8e5-44733a108245

**Comment by DevAgu93** [comment]
Here it shows better what I'm talking about.

https://github.com/EpicGames/raddebugger/assets/63572671/653fbc92-0684-4db7-8070-f398ed89fcfe

**Comment by ryanfleury** [comment]
Hm, alright, I'm experimenting with this. Apparently the debugger is still receiving WM_MOUSEMOVEs even when the mouse is over an occluded part of its client area? It looks like this changes if I move my mouse sufficiently within another window's client area, but this doesn't appear to happen with other applications, so I'll need to figure out what I did to make this happen.

**Comment by ryanfleury** [comment]
Alright, this should be fixed now as of d139c2874cbc75fa0ebddeb53be1d88002f83812. I still receive `WM_MOUSEMOVE`s when the mouse moves over an occluding window, which is a bit confusing to me (but is perhaps standard behavior, perhaps made less confusing by the behavior of `DefWindowProc` in those cases), but the debugger doesn't actually respond to those events at all in any case. It instead does its mouse position testing based on a polled position. Because the mouse position was persistently changing, irrespective of whether or not the debugger window was focused, it was constantly animating buttons, thus causing persistent refreshing.

The normal behavior seems to be to not respond to mouse position changes at all if the window is not focused, and so I've updated the debugger's behavior to reflect this.

**Comment by DevAgu93** [comment]
Pull, build and tested again, but the issue persists for me.

**Comment by ryanfleury** [comment]
Can you show a video demonstrating your mouse movement over your game window, while the debugger is in the background, with the updating indicator continuously bobbing?

**Comment by DevAgu93** [comment]
Of course

https://github.com/EpicGames/raddebugger/assets/63572671/3fafff06-9057-4897-94a9-075d9f6d055c

**Comment by ryanfleury** [comment]
And what does `git rev-parse HEAD` return for you?

**Comment by DevAgu93** [comment]
![image](https://github.com/EpicGames/raddebugger/assets/63572671/5cd3ab3c-1da9-4b06-a4ad-f1ef4450e14c)

**Comment by ryanfleury** [comment]
You're not on the `dev` branch. You need to run `git checkout dev`, then `git pull`, then try building & running again.

**Comment by DevAgu93** [comment]
While not focused:
![image](https://github.com/EpicGames/raddebugger/assets/63572671/2a709628-08bc-49f1-a667-24a434f67ed6)
While focused:
![image](https://github.com/EpicGames/raddebugger/assets/63572671/2ddf0362-45b9-4625-9a66-8d82038cf05f)

The high CPU usage occurs while I move my mouse, but not when staying idle. Seems like everything works as intended now :)

**Comment by mmozeiko** [comment]
For reduced GPU usage you can try running release radbbg binary - debug builds do not have optimization enabled. And debug build enables D3D11 debug layer by default which can affect GPU performance.

**Comment by DevAgu93** [comment]
I tried compiling on release but it takes forever to build. I think something is wrong, or I did something wrong. I used the bat with "raddbg release"

**Comment by jeffatrad** [comment]
We may want to make the D3D11 debug layer turned on with a commandline switch instead of debug mode, maybe.  Might as well not double down the slowness when you might just be debugging something CPU side...

@DevAgu93 In release mode, on my machine, it takes about 2 mins to build, if you want a estimate of how long it will take.  We could probably turn a switch down or two to speed up that compile...

**Comment by DevAgu93** [comment]
That would help if it's no bother. Otherwise I could let my pc compiling while afk as well.
